use_frameworks!
source 'https://github.com/media-net/mnet-pod-specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'MNetDfpHbSdk_Example' do
  pod 'MNetDfpHbSdk', :path => '../'
  pod 'MBProgressHUD'
  pod 'Toast', '~> 3.1.0'

  platform :ios, '9.0'

  target 'MNetDfpHbSdk_Tests' do
    inherit! :search_paths
    pod 'KIF', git: 'https://github.com/kif-framework/KIF.git', branch: 'master'
    pod 'NetworkEye'
    pod 'Nocilla'
  end
end

# Kindly ignore this if the framework is being used
# NOTE: Make sure that when testing the framework app, this is removed
pre_install do |installer|

  # NOTE: Replace verify_no_static_framework_transitive_dependencies method definition with {} for ad-sdk to build
  installer.pod_targets.each do |pod|
        if pod.name == "MNetDfpHbSdk"
            puts "********************"
            puts "*** Overriding the verify_no_static_framework_transitive_dependencies method for MNetDfpHbSdk ***"
            puts "********************"
            Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
        end
      end

  # NOTE: We do not need DFP_POD_FMK='NO' for ad-sdk to build. Do not remove this code, may be used in future. 
  if ENV['DFP_POD_FMK'] == "NO"
      installer.pod_targets.each do |pod|
        if pod.name == "MNetDfpHbSdk"
            puts "********************"
            puts "*** Overriding the static_framework? method for MNetDfpHbSdk ***"
            puts "*** NOTE: If using framework, set env var. `export DFP_POD_FMK='YES'`"
            puts "********************"
            def pod.static_framework?;
              true
            end
        end
      end
  else
      puts "********************"
      puts "*** Not enabling static framework ***"
      puts "*** If using pod-source-files, set env var. `export DFP_POD_FMK='NO'` for ad-sdk to build. Else it will fail ***"
      puts "********************"
  end
end